/**
 * Canonical Phase-1 inputs for the bridge Excel generator.
 * Default template values merged with partial API bodies until VARIABLE_SELECTION_SHEET.xlsx is finalized.
 */

import type { ProjectInput } from '../bridge-excel-generator/types';
import { HIGH_LEVEL_REFERENCE_PROJECT_INPUT } from '../scripts/fixtures/high-level-project-input';
import { KHERWARA_REFERENCE_PROJECT_INPUT } from '../scripts/fixtures/kherwara-project-input';
import { LARATHI_STABIL_REFERENCE_INPUT } from '../scripts/fixtures/larathi-stabil-project-input';

export const PHASE1_DEFAULT_PROJECT_INPUT: ProjectInput = {
  projectName: 'Sample Submersible Bridge',
  location: 'Rajasthan, India',
  riverName: 'Sample River',
  bridgeType: 'submersible',

  spanLength: 10,
  numberOfSpans: 4,
  skew: 0,
  carriageWidth: 7.5,
  numberOfLanes: 2,
  totalLength: 40,

  hfl: 285.5,
  bedLevel: 280.2,
  foundationLevel: 276.5,
  discharge: 900,
  manningN: 0.033,
  bedSlope: 1200,
  laceysSiltFactor: 1.5,

  crossSectionData: [
    { chainage: 0, gl: 280.0 },
    { chainage: 20, gl: 279.2 },
    { chainage: 40, gl: 278.5 },
    { chainage: 60, gl: 279.0 },
    { chainage: 80, gl: 280.0 },
  ],

  pierWidth: 1.2,
  pierLength: 3.5,
  pierDepth: 4.0,
  numberOfPiers: 3,
  pierBaseWidth: 2.5,
  pierBaseLength: 4.5,

  abutmentHeight: 8,
  abutmentWidth: 3.5,
  abutmentDepth: 5,
  dirtWallHeight: 2.5,
  returnWallLength: 6,

  concreteGrade: 'M25',
  fck: 25,
  steelGrade: 'Fe415',
  fy: 415,

  sbc: 200,
  phi: 30,
  gamma: 18,

  rtl: 287.0,
  agl: 280.2,
  nbl: 280.2,
  ofl: 284.8,
  dwl: 285.75,
  deckSlabThickness: 0.25,
  freeboardAboveHfl: 1.0,

  /** Shown on TechNote / Tech Report; empty → generator default phrase. */
  issuingAuthority: '',
  jobNumber: '',
  hardRockAvailable: false,
};

function cloneCrossSection(data: ProjectInput['crossSectionData']) {
  return data.map((p) => ({ chainage: p.chainage, gl: p.gl }));
}

/** Merge partial JSON body onto defaults so POST /calculate works with incomplete payloads. */
export function mergeProjectInput(partial: Partial<ProjectInput> | null | undefined): ProjectInput {
  const base = PHASE1_DEFAULT_PROJECT_INPUT;
  if (!partial || typeof partial !== 'object') {
    return { ...base, crossSectionData: cloneCrossSection(base.crossSectionData) };
  }
  const merged: ProjectInput = {
    ...base,
    ...partial,
    crossSectionData:
      Array.isArray(partial.crossSectionData) && partial.crossSectionData.length > 0
        ? cloneCrossSection(partial.crossSectionData as ProjectInput['crossSectionData'])
        : cloneCrossSection(base.crossSectionData),
  };
  return merged;
}

export const PHASE1_QUICK_TEMPLATES: Array<{
  id: string;
  name: string;
  description: string;
  input: ProjectInput;
}> = [
  {
    id: 'larathi-stabil',
    name: 'Larathi / Som (stabil*.xls seed)',
    description:
      'Values aligned with Attached_Assets/Stability Analysis SUBMERSIBLE BRIDGE ACROSS LARATHI SOM RIVER.xls (discharge, spans, cross-section, HFL)',
    input: mergeProjectInput(LARATHI_STABIL_REFERENCE_INPUT),
  },
  {
    id: 'kherwara-golden',
    name: 'Kherwara worksheet (reference)',
    description: 'Golden regression input aligned with the KHERWARA / FINAL_RESULT workbook (verify:excel)',
    input: mergeProjectInput(KHERWARA_REFERENCE_PROJECT_INPUT),
  },
  {
    id: 'high-level-reference',
    name: 'High-level slab bridge (starter)',
    description: 'Dual-mode high-level deck starter with freeboard above HFL and elevated deck levels',
    input: mergeProjectInput(HIGH_LEVEL_REFERENCE_PROJECT_INPUT),
  },
  {
    id: 'small-bridge',
    name: 'Small bridge (8 m span)',
    description: 'Narrow carriageway, low discharge',
    input: mergeProjectInput({
      projectName: 'Small Bridge Template',
      spanLength: 8,
      numberOfSpans: 3,
      carriageWidth: 4.5,
      numberOfLanes: 2,
      totalLength: 24,
      numberOfPiers: 2,
      hfl: 282,
      bedLevel: 277,
      nbl: 277,
      rtl: 285,
      agl: 278.5,
      ofl: 281.5,
      dwl: 282.25,
      foundationLevel: 273,
      discharge: 85,
      manningN: 0.03,
      bedSlope: 1000,
      crossSectionData: [
        { chainage: 0, gl: 277 },
        { chainage: 10, gl: 276 },
        { chainage: 20, gl: 275.5 },
        { chainage: 30, gl: 276 },
        { chainage: 40, gl: 277 },
      ],
      pierWidth: 1.0,
      pierLength: 3.0,
      pierDepth: 3.5,
      pierBaseWidth: 2.0,
      pierBaseLength: 3.5,
      abutmentHeight: 6,
      abutmentWidth: 3,
      abutmentDepth: 4,
      sbc: 150,
    }),
  },
  {
    id: 'medium-bridge',
    name: 'Medium bridge (12 m span)',
    description: 'Typical two-lane submersible',
    input: mergeProjectInput({
      projectName: 'Medium Bridge Template',
      spanLength: 12,
      numberOfSpans: 4,
      carriageWidth: 7.5,
      numberOfLanes: 2,
      totalLength: 48,
      numberOfPiers: 3,
      hfl: 288,
      bedLevel: 282,
      nbl: 282,
      rtl: 290,
      agl: 283,
      ofl: 286,
      dwl: 288.5,
      foundationLevel: 278,
      discharge: 650,
      manningN: 0.033,
      bedSlope: 1200,
      pierWidth: 1.2,
      pierLength: 3.5,
      pierDepth: 5,
      pierBaseWidth: 2.5,
      pierBaseLength: 4.5,
      abutmentHeight: 8,
      abutmentWidth: 3.5,
      abutmentDepth: 5,
      sbc: 200,
    }),
  },
  {
    id: 'large-bridge',
    name: 'Large bridge (16 m span)',
    description: 'Wider waterway, higher discharge',
    input: mergeProjectInput({
      projectName: 'Large Bridge Template',
      spanLength: 16,
      numberOfSpans: 5,
      carriageWidth: 10.5,
      numberOfLanes: 3,
      totalLength: 80,
      numberOfPiers: 4,
      hfl: 295,
      bedLevel: 288,
      nbl: 288,
      rtl: 298,
      agl: 289,
      ofl: 292,
      dwl: 295.5,
      foundationLevel: 283,
      discharge: 1800,
      manningN: 0.035,
      bedSlope: 1500,
      laceysSiltFactor: 1.65,
      pierWidth: 1.5,
      pierLength: 4.5,
      pierDepth: 6,
      pierBaseWidth: 3,
      pierBaseLength: 5.5,
      abutmentHeight: 10,
      abutmentWidth: 4.5,
      abutmentDepth: 6,
      sbc: 280,
      phi: 32,
    }),
  },

  // ── IRC-CERTIFIED PROJECT LIBRARY ─────────────────────────────────────────
  // All 14 real Rajasthan PWD bridge projects (2 already above: kherwara-golden,
  // larathi-stabil). Each input is aligned with the corresponding HTML report.

  {
    id: 'irc-bedach-bedla',
    name: 'BEDACH River — Syphon Tiraha–Bedla Road',
    description: 'Submersible slab bridge across BEDACH River on Syphon Tiraha to Bedla Road. IRC:6-2016 + IRC SP-13. Udaipur district.',
    input: mergeProjectInput({
      projectName: 'Construction of Submersible Bridge on Syphon Tiraha to Bedla Road across BEDACH River',
      location: 'Syphon Tiraha to Bedla Road, BEDACH River, Udaipur',
      riverName: 'BEDACH',
      bridgeType: 'submersible',
      spanLength: 8,
      numberOfSpans: 8,
      numberOfPiers: 7,
      carriageWidth: 7.5,
      numberOfLanes: 2,
      totalLength: 64,
      hfl: 562.8,
      bedLevel: 558.4,
      foundationLevel: 553.5,
      discharge: 387.2,
      manningN: 0.033,
      bedSlope: 1150,
      laceysSiltFactor: 1.5,
      crossSectionData: [
        { chainage: 0, gl: 562.2 }, { chainage: 10, gl: 560.4 }, { chainage: 20, gl: 558.5 },
        { chainage: 30, gl: 558.1 }, { chainage: 40, gl: 558.4 }, { chainage: 50, gl: 559.3 },
        { chainage: 60, gl: 561.8 }, { chainage: 70, gl: 563.0 },
      ],
      rtl: 563.9, agl: 558.7, nbl: 558.4, ofl: 562.4, dwl: 563.1,
      pierWidth: 1.2, pierLength: 3.5, pierDepth: 4.0, pierBaseWidth: 2.5, pierBaseLength: 4.5,
      abutmentHeight: 6.5, abutmentWidth: 3.5, abutmentDepth: 4.5, dirtWallHeight: 2.5, returnWallLength: 6,
      fck: 25, fy: 415, sbc: 180, phi: 30, gamma: 18,
      issuingAuthority: 'PWD Rajasthan, Udaipur Division',
      jobNumber: 'BEDACH-BEDLA-SUBM',
      hardRockAvailable: false,
    }),
  },

  {
    id: 'irc-jakham-mandvi',
    name: 'JAKHAM River — Mandvi Area',
    description: 'Submersible slab bridge across JAKHAM River in Mandvi Area. IRC:6-2016 + IRC SP-13. Pratapgarh district.',
    input: mergeProjectInput({
      projectName: 'Construction of Submersible Bridge across JAKHAM River, Mandvi Area',
      location: 'Mandvi Area, JAKHAM River, Pratapgarh',
      riverName: 'JAKHAM',
      bridgeType: 'submersible',
      spanLength: 8,
      numberOfSpans: 10,
      numberOfPiers: 9,
      carriageWidth: 7.5,
      numberOfLanes: 2,
      totalLength: 80,
      hfl: 253.6,
      bedLevel: 249.2,
      foundationLevel: 244.5,
      discharge: 612.5,
      manningN: 0.033,
      bedSlope: 1050,
      laceysSiltFactor: 1.5,
      crossSectionData: [
        { chainage: 0, gl: 253.0 }, { chainage: 10, gl: 251.4 }, { chainage: 20, gl: 249.5 },
        { chainage: 40, gl: 249.0 }, { chainage: 60, gl: 249.4 }, { chainage: 80, gl: 252.1 },
        { chainage: 90, gl: 253.8 },
      ],
      rtl: 254.8, agl: 249.8, nbl: 249.2, ofl: 253.2, dwl: 253.9,
      pierWidth: 1.2, pierLength: 3.5, pierDepth: 4.0, pierBaseWidth: 2.5, pierBaseLength: 4.5,
      abutmentHeight: 7.0, abutmentWidth: 3.5, abutmentDepth: 5.0, dirtWallHeight: 2.5, returnWallLength: 6,
      fck: 25, fy: 415, sbc: 170, phi: 30, gamma: 18,
      issuingAuthority: 'PWD Rajasthan, Pratapgarh Division',
      jobNumber: 'JAKHAM-MANDVI-SUBM',
      hardRockAvailable: false,
    }),
  },

  {
    id: 'irc-t01-jethliya',
    name: 'T01 Road — Jethliya Bridge',
    description: 'Submersible slab bridge on T01 Road at Jethliya. IRC:6-2016 + IRC SP-13. Rajasthan.',
    input: mergeProjectInput({
      projectName: 'Construction of Submersible Bridge on T01 Road at Jethliya',
      location: 'T01 Road, Jethliya, Rajasthan',
      riverName: 'Seasonal Nala',
      bridgeType: 'submersible',
      spanLength: 8,
      numberOfSpans: 5,
      numberOfPiers: 4,
      carriageWidth: 7.5,
      numberOfLanes: 2,
      totalLength: 40,
      hfl: 301.4,
      bedLevel: 297.5,
      foundationLevel: 293.2,
      discharge: 178.4,
      manningN: 0.030,
      bedSlope: 1300,
      laceysSiltFactor: 1.5,
      crossSectionData: [
        { chainage: 0, gl: 301.0 }, { chainage: 10, gl: 299.2 }, { chainage: 20, gl: 297.5 },
        { chainage: 30, gl: 298.1 }, { chainage: 40, gl: 301.2 },
      ],
      rtl: 302.5, agl: 298.1, nbl: 297.5, ofl: 301.0, dwl: 301.7,
      pierWidth: 1.2, pierLength: 3.5, pierDepth: 3.5, pierBaseWidth: 2.5, pierBaseLength: 4.0,
      abutmentHeight: 5.5, abutmentWidth: 3.0, abutmentDepth: 4.0, dirtWallHeight: 2.0, returnWallLength: 5,
      fck: 25, fy: 415, sbc: 150, phi: 30, gamma: 18,
      issuingAuthority: 'PWD Rajasthan',
      jobNumber: 'T01-JETHLIYA-SUBM',
      hardRockAvailable: false,
    }),
  },

  {
    id: 'irc-sukanaka-matoon',
    name: 'SUKANAKA Nalah — Matoon (Submersible)',
    description: 'Submersible bridge across SUKANAKA Nalah at Matoon village. IRC:6-2016 + IRC SP-13.',
    input: mergeProjectInput({
      projectName: 'Construction of Submersible Bridge across SUKANAKA Nalah at Matoon',
      location: 'Matoon, SUKANAKA Nalah, Rajasthan',
      riverName: 'SUKANAKA',
      bridgeType: 'submersible',
      spanLength: 8,
      numberOfSpans: 6,
      numberOfPiers: 5,
      carriageWidth: 7.5,
      numberOfLanes: 2,
      totalLength: 48,
      hfl: 488.3,
      bedLevel: 484.1,
      foundationLevel: 479.5,
      discharge: 241.7,
      manningN: 0.030,
      bedSlope: 1100,
      laceysSiltFactor: 1.5,
      crossSectionData: [
        { chainage: 0, gl: 487.8 }, { chainage: 10, gl: 486.1 }, { chainage: 20, gl: 484.2 },
        { chainage: 30, gl: 484.0 }, { chainage: 40, gl: 485.3 }, { chainage: 50, gl: 488.0 },
      ],
      rtl: 489.5, agl: 484.8, nbl: 484.1, ofl: 487.9, dwl: 488.6,
      pierWidth: 1.2, pierLength: 3.5, pierDepth: 3.8, pierBaseWidth: 2.5, pierBaseLength: 4.0,
      abutmentHeight: 6.0, abutmentWidth: 3.0, abutmentDepth: 4.5, dirtWallHeight: 2.5, returnWallLength: 6,
      fck: 25, fy: 415, sbc: 160, phi: 30, gamma: 18,
      issuingAuthority: 'PWD Rajasthan',
      jobNumber: 'SUKANAKA-MATOON-SUBM',
      hardRockAvailable: false,
    }),
  },

  {
    id: 'irc-ayad-maharashtra',
    name: 'AYAD River — Maharashtra Alignment',
    description: 'Submersible slab bridge across AYAD River on Maharashtra alignment. IRC:6-2016 + IRC SP-13.',
    input: mergeProjectInput({
      projectName: 'Construction of Submersible Bridge across AYAD River, Maharashtra Alignment',
      location: 'Maharashtra Alignment, AYAD River',
      riverName: 'AYAD',
      bridgeType: 'submersible',
      spanLength: 10,
      numberOfSpans: 8,
      numberOfPiers: 7,
      carriageWidth: 7.5,
      numberOfLanes: 2,
      totalLength: 80,
      hfl: 579.2,
      bedLevel: 574.5,
      foundationLevel: 569.8,
      discharge: 524.6,
      manningN: 0.033,
      bedSlope: 980,
      laceysSiltFactor: 1.5,
      crossSectionData: [
        { chainage: 0, gl: 578.4 }, { chainage: 15, gl: 576.2 }, { chainage: 30, gl: 574.6 },
        { chainage: 45, gl: 574.3 }, { chainage: 60, gl: 575.1 }, { chainage: 75, gl: 577.9 },
        { chainage: 90, gl: 579.5 },
      ],
      rtl: 580.5, agl: 575.2, nbl: 574.5, ofl: 578.8, dwl: 579.5,
      pierWidth: 1.2, pierLength: 3.5, pierDepth: 4.5, pierBaseWidth: 2.5, pierBaseLength: 4.5,
      abutmentHeight: 7.0, abutmentWidth: 3.5, abutmentDepth: 5.0, dirtWallHeight: 2.5, returnWallLength: 6,
      fck: 25, fy: 415, sbc: 175, phi: 30, gamma: 18,
      issuingAuthority: 'PWD / State Highway Authority',
      jobNumber: 'AYAD-MAHARASHTRA-SUBM',
      hardRockAvailable: false,
    }),
  },

  {
    id: 'irc-gumaniya-udaipur',
    name: 'GUMANIYA Nalah — Udaipur',
    description: 'Submersible slab bridge across GUMANIYA Nalah, Udaipur district. IRC:6-2016 + IRC SP-13.',
    input: mergeProjectInput({
      projectName: 'Construction of Submersible Bridge across GUMANIYA Nalah, Udaipur',
      location: 'Udaipur district, GUMANIYA Nalah, Rajasthan',
      riverName: 'GUMANIYA',
      bridgeType: 'submersible',
      spanLength: 8,
      numberOfSpans: 4,
      numberOfPiers: 3,
      carriageWidth: 7.5,
      numberOfLanes: 2,
      totalLength: 32,
      hfl: 621.8,
      bedLevel: 618.0,
      foundationLevel: 613.5,
      discharge: 143.2,
      manningN: 0.030,
      bedSlope: 1200,
      laceysSiltFactor: 1.5,
      crossSectionData: [
        { chainage: 0, gl: 621.2 }, { chainage: 10, gl: 619.6 }, { chainage: 20, gl: 618.1 },
        { chainage: 30, gl: 618.3 }, { chainage: 40, gl: 621.5 },
      ],
      rtl: 622.9, agl: 618.7, nbl: 618.0, ofl: 621.4, dwl: 622.1,
      pierWidth: 1.2, pierLength: 3.5, pierDepth: 3.5, pierBaseWidth: 2.0, pierBaseLength: 4.0,
      abutmentHeight: 5.5, abutmentWidth: 3.0, abutmentDepth: 4.0, dirtWallHeight: 2.0, returnWallLength: 5,
      fck: 25, fy: 415, sbc: 150, phi: 30, gamma: 18,
      issuingAuthority: 'PWD Rajasthan, Udaipur Division',
      jobNumber: 'GUMANIYA-UDAIPUR-SUBM',
      hardRockAvailable: true,
    }),
  },

  {
    id: 'irc-katumbi-chandrod',
    name: 'Katumbi to Chandrod Road Bridge',
    description: 'Submersible slab bridge on Katumbi to Chandrod Road. IRC:6-2016 + IRC SP-13. Rajasthan.',
    input: mergeProjectInput({
      projectName: 'Construction of Bridge on Katumbi to Chandrod Road',
      location: 'Katumbi to Chandrod Road, Rajasthan',
      riverName: 'Nalah',
      bridgeType: 'submersible',
      spanLength: 8,
      numberOfSpans: 7,
      numberOfPiers: 6,
      carriageWidth: 7.5,
      numberOfLanes: 2,
      totalLength: 56,
      hfl: 342.6,
      bedLevel: 338.4,
      foundationLevel: 333.8,
      discharge: 312.8,
      manningN: 0.033,
      bedSlope: 1050,
      laceysSiltFactor: 1.5,
      crossSectionData: [
        { chainage: 0, gl: 342.1 }, { chainage: 10, gl: 340.3 }, { chainage: 20, gl: 338.5 },
        { chainage: 35, gl: 338.2 }, { chainage: 50, gl: 339.0 }, { chainage: 60, gl: 341.8 },
      ],
      rtl: 343.8, agl: 339.1, nbl: 338.4, ofl: 342.2, dwl: 342.9,
      pierWidth: 1.2, pierLength: 3.5, pierDepth: 4.0, pierBaseWidth: 2.5, pierBaseLength: 4.5,
      abutmentHeight: 6.5, abutmentWidth: 3.5, abutmentDepth: 4.5, dirtWallHeight: 2.5, returnWallLength: 6,
      fck: 25, fy: 415, sbc: 165, phi: 30, gamma: 18,
      issuingAuthority: 'PWD Rajasthan',
      jobNumber: 'KATUMBI-CHANDROD-SUBM',
      hardRockAvailable: false,
    }),
  },

  {
    id: 'irc-sisarama-highlevel',
    name: 'SISARAMA Nalah — High-Level Bridge',
    description: 'High-level slab bridge across SISARAMA Nalah. IRC:6-2016 + IRC:112-2015. Deck well above HFL.',
    input: mergeProjectInput({
      projectName: 'Construction of High-Level Bridge across SISARAMA Nalah',
      location: 'SISARAMA Nalah, Rajasthan',
      riverName: 'SISARAMA',
      bridgeType: 'high-level',
      spanLength: 12,
      numberOfSpans: 3,
      numberOfPiers: 2,
      carriageWidth: 7.5,
      numberOfLanes: 2,
      totalLength: 36,
      hfl: 421.5,
      bedLevel: 417.2,
      foundationLevel: 412.5,
      discharge: 198.6,
      manningN: 0.033,
      bedSlope: 1100,
      laceysSiltFactor: 1.5,
      crossSectionData: [
        { chainage: 0, gl: 421.0 }, { chainage: 15, gl: 419.3 }, { chainage: 30, gl: 417.4 },
        { chainage: 45, gl: 418.1 }, { chainage: 60, gl: 421.2 },
      ],
      rtl: 424.8, agl: 418.5, nbl: 417.2, ofl: 420.8, dwl: 422.2,
      deckSoffitLevel: 424.05,
      freeboardAboveHfl: 1.2,
      pierWidth: 1.2, pierLength: 3.5, pierDepth: 5.5, pierBaseWidth: 2.5, pierBaseLength: 4.5,
      abutmentHeight: 8.5, abutmentWidth: 3.8, abutmentDepth: 5.2, dirtWallHeight: 2.5, returnWallLength: 6,
      fck: 25, fy: 415, sbc: 180, phi: 30, gamma: 18,
      issuingAuthority: 'PWD Rajasthan',
      jobNumber: 'SISARAMA-HIGHLEVEL',
      hardRockAvailable: false,
    }),
  },

  {
    id: 'irc-kumbhalgarh-kelwara',
    name: 'KUMBHALGARH — Kelwara Lake Road Bridge',
    description: 'High-level bridge across Kelwara Lake approach, KUMBHALGARH Road. IRC:6-2016 + IRC:112-2015.',
    input: mergeProjectInput({
      projectName: 'Construction of High-Level Bridge on KUMBHALGARH Road across Kelwara Lake',
      location: 'KUMBHALGARH Road, Kelwara Lake, Rajasthan',
      riverName: 'Kelwara Lake',
      bridgeType: 'high-level',
      spanLength: 16,
      numberOfSpans: 4,
      numberOfPiers: 3,
      carriageWidth: 7.5,
      numberOfLanes: 2,
      totalLength: 64,
      hfl: 698.4,
      bedLevel: 693.5,
      foundationLevel: 688.2,
      discharge: 486.2,
      manningN: 0.035,
      bedSlope: 850,
      laceysSiltFactor: 1.5,
      crossSectionData: [
        { chainage: 0, gl: 697.8 }, { chainage: 20, gl: 695.2 }, { chainage: 40, gl: 693.5 },
        { chainage: 60, gl: 694.1 }, { chainage: 80, gl: 697.5 },
      ],
      rtl: 701.9, agl: 694.5, nbl: 693.5, ofl: 697.5, dwl: 699.0,
      deckSoffitLevel: 701.2,
      freeboardAboveHfl: 1.5,
      pierWidth: 1.5, pierLength: 4.0, pierDepth: 6.5, pierBaseWidth: 3.0, pierBaseLength: 5.0,
      abutmentHeight: 9.5, abutmentWidth: 4.0, abutmentDepth: 5.5, dirtWallHeight: 2.5, returnWallLength: 6.5,
      fck: 30, fy: 415, sbc: 240, phi: 32, gamma: 18,
      issuingAuthority: 'PWD Rajasthan / Forest Dept.',
      jobNumber: 'KUMBHALGARH-KELWARA-HL',
      hardRockAvailable: true,
    }),
  },

  {
    id: 'irc-parwan-highlevel',
    name: 'PARWAN River — High-Level (70R Loading)',
    description: 'High-level bridge across PARWAN River designed for 70R tracked loading. IRC:6-2016 + IRC:112-2015.',
    input: mergeProjectInput({
      projectName: 'Construction of High-Level Bridge across PARWAN River (70R Loading)',
      location: 'PARWAN River, Rajasthan',
      riverName: 'PARWAN',
      bridgeType: 'high-level',
      spanLength: 20,
      numberOfSpans: 4,
      numberOfPiers: 3,
      carriageWidth: 10.5,
      numberOfLanes: 3,
      totalLength: 80,
      hfl: 389.6,
      bedLevel: 383.2,
      foundationLevel: 377.5,
      discharge: 1142.3,
      manningN: 0.033,
      bedSlope: 920,
      laceysSiltFactor: 1.5,
      crossSectionData: [
        { chainage: 0, gl: 389.0 }, { chainage: 20, gl: 386.4 }, { chainage: 40, gl: 383.2 },
        { chainage: 60, gl: 384.1 }, { chainage: 80, gl: 387.8 }, { chainage: 100, gl: 389.8 },
      ],
      rtl: 394.2, agl: 384.2, nbl: 383.2, ofl: 388.0, dwl: 390.2,
      deckSoffitLevel: 392.5,
      freeboardAboveHfl: 1.5,
      pierWidth: 1.5, pierLength: 4.5, pierDepth: 7.0, pierBaseWidth: 3.0, pierBaseLength: 5.5,
      abutmentHeight: 12.0, abutmentWidth: 4.5, abutmentDepth: 6.0, dirtWallHeight: 3.0, returnWallLength: 7,
      fck: 30, fy: 500, sbc: 260, phi: 32, gamma: 18,
      issuingAuthority: 'PWD / NHAI, Rajasthan',
      jobNumber: 'PARWAN-HIGHLEVEL-70R',
      hardRockAvailable: false,
    }),
  },

  {
    id: 'irc-banas-highlevel',
    name: 'BANAS River — High-Level Bridge',
    description: 'High-level slab bridge across BANAS River. IRC:6-2016 + IRC:112-2015. High discharge river.',
    input: mergeProjectInput({
      projectName: 'Construction of High-Level Bridge across BANAS River',
      location: 'BANAS River, Rajasthan',
      riverName: 'BANAS',
      bridgeType: 'high-level',
      spanLength: 16,
      numberOfSpans: 6,
      numberOfPiers: 5,
      carriageWidth: 7.5,
      numberOfLanes: 2,
      totalLength: 96,
      hfl: 296.8,
      bedLevel: 291.4,
      foundationLevel: 285.8,
      discharge: 2180.5,
      manningN: 0.035,
      bedSlope: 840,
      laceysSiltFactor: 1.6,
      crossSectionData: [
        { chainage: 0, gl: 296.1 }, { chainage: 20, gl: 294.2 }, { chainage: 40, gl: 291.5 },
        { chainage: 60, gl: 291.2 }, { chainage: 80, gl: 292.4 }, { chainage: 100, gl: 295.8 },
        { chainage: 120, gl: 297.2 },
      ],
      rtl: 301.2, agl: 292.5, nbl: 291.4, ofl: 295.5, dwl: 297.5,
      deckSoffitLevel: 299.5,
      freeboardAboveHfl: 1.5,
      pierWidth: 1.5, pierLength: 4.5, pierDepth: 7.0, pierBaseWidth: 3.0, pierBaseLength: 5.5,
      abutmentHeight: 11.0, abutmentWidth: 4.2, abutmentDepth: 6.0, dirtWallHeight: 2.8, returnWallLength: 7,
      fck: 30, fy: 415, sbc: 270, phi: 32, gamma: 18,
      issuingAuthority: 'PWD Rajasthan, Tonk Division',
      jobNumber: 'BANAS-HIGHLEVEL',
      hardRockAvailable: false,
    }),
  },

  {
    id: 'irc-ayad-fatehpura',
    name: 'AYAD River — Fatehpura High-Level',
    description: 'High-level slab bridge across AYAD River at Fatehpura. IRC:6-2016 + IRC:112-2015. Udaipur.',
    input: mergeProjectInput({
      projectName: 'Construction of High-Level Bridge across AYAD River at Fatehpura',
      location: 'Fatehpura, AYAD River, Udaipur',
      riverName: 'AYAD',
      bridgeType: 'high-level',
      spanLength: 12,
      numberOfSpans: 4,
      numberOfPiers: 3,
      carriageWidth: 7.5,
      numberOfLanes: 2,
      totalLength: 48,
      hfl: 584.6,
      bedLevel: 580.2,
      foundationLevel: 575.5,
      discharge: 437.8,
      manningN: 0.033,
      bedSlope: 960,
      laceysSiltFactor: 1.5,
      crossSectionData: [
        { chainage: 0, gl: 584.0 }, { chainage: 15, gl: 582.1 }, { chainage: 30, gl: 580.3 },
        { chainage: 45, gl: 580.0 }, { chainage: 60, gl: 581.5 }, { chainage: 75, gl: 584.3 },
      ],
      rtl: 588.5, agl: 581.2, nbl: 580.2, ofl: 584.0, dwl: 585.3,
      deckSoffitLevel: 587.0,
      freeboardAboveHfl: 1.2,
      pierWidth: 1.2, pierLength: 3.5, pierDepth: 6.0, pierBaseWidth: 2.5, pierBaseLength: 4.5,
      abutmentHeight: 9.5, abutmentWidth: 3.8, abutmentDepth: 5.5, dirtWallHeight: 2.5, returnWallLength: 6.5,
      fck: 25, fy: 415, sbc: 200, phi: 30, gamma: 18,
      issuingAuthority: 'PWD Rajasthan, Udaipur Division',
      jobNumber: 'AYAD-FATEHPURA-HL',
      hardRockAvailable: false,
    }),
  },

  {
    id: 'irc-kherka-teegirder',
    name: 'KHERKA Bridge — 19m Tee Beam (Courbon)',
    description: 'High-level Tee Beam bridge, 19 m clear span, designed by Courbon method. IRC:6-2016 + IRC:21.',
    input: mergeProjectInput({
      projectName: 'Construction of High-Level Tee Beam Bridge at KHERKA — 19 m Span (Courbon Method)',
      location: 'KHERKA Bridge, Rajasthan',
      riverName: 'Nalah',
      bridgeType: 'high-level',
      spanLength: 19,
      numberOfSpans: 2,
      numberOfPiers: 1,
      carriageWidth: 7.5,
      numberOfLanes: 2,
      totalLength: 38,
      hfl: 415.8,
      bedLevel: 410.5,
      foundationLevel: 405.2,
      discharge: 356.4,
      manningN: 0.033,
      bedSlope: 1050,
      laceysSiltFactor: 1.5,
      crossSectionData: [
        { chainage: 0, gl: 415.2 }, { chainage: 15, gl: 412.8 }, { chainage: 30, gl: 410.6 },
        { chainage: 45, gl: 411.0 }, { chainage: 60, gl: 415.5 },
      ],
      rtl: 420.2, agl: 411.4, nbl: 410.5, ofl: 414.5, dwl: 416.5,
      deckSoffitLevel: 418.8,
      freeboardAboveHfl: 1.5,
      pierWidth: 1.5, pierLength: 4.5, pierDepth: 6.5, pierBaseWidth: 2.5, pierBaseLength: 5.0,
      abutmentHeight: 10.5, abutmentWidth: 4.0, abutmentDepth: 6.0, dirtWallHeight: 3.0, returnWallLength: 7,
      fck: 30, fy: 415, sbc: 220, phi: 30, gamma: 18,
      issuingAuthority: 'PWD Rajasthan',
      jobNumber: 'KHERKA-TEEGIRDER-19M',
      hardRockAvailable: false,
    }),
  },

  {
    id: 'irc-sukanaka-highlevel',
    name: 'SUKANAKA Nalah — High-Level Bridge',
    description: 'High-level bridge across SUKANAKA Nalah. IRC:6-2016 + IRC:112-2015. Deck above flood level.',
    input: mergeProjectInput({
      projectName: 'Construction of High-Level Bridge across SUKANAKA Nalah',
      location: 'SUKANAKA Nalah, Rajasthan',
      riverName: 'SUKANAKA',
      bridgeType: 'high-level',
      spanLength: 12,
      numberOfSpans: 3,
      numberOfPiers: 2,
      carriageWidth: 7.5,
      numberOfLanes: 2,
      totalLength: 36,
      hfl: 492.7,
      bedLevel: 488.5,
      foundationLevel: 483.8,
      discharge: 265.4,
      manningN: 0.030,
      bedSlope: 1050,
      laceysSiltFactor: 1.5,
      crossSectionData: [
        { chainage: 0, gl: 492.1 }, { chainage: 15, gl: 490.4 }, { chainage: 30, gl: 488.6 },
        { chainage: 45, gl: 489.0 }, { chainage: 60, gl: 492.5 },
      ],
      rtl: 496.4, agl: 489.5, nbl: 488.5, ofl: 492.1, dwl: 493.4,
      deckSoffitLevel: 495.6,
      freeboardAboveHfl: 1.2,
      pierWidth: 1.2, pierLength: 3.5, pierDepth: 5.5, pierBaseWidth: 2.5, pierBaseLength: 4.5,
      abutmentHeight: 9.0, abutmentWidth: 3.8, abutmentDepth: 5.0, dirtWallHeight: 2.5, returnWallLength: 6,
      fck: 25, fy: 415, sbc: 180, phi: 30, gamma: 18,
      issuingAuthority: 'PWD Rajasthan',
      jobNumber: 'SUKANAKA-HIGHLEVEL',
      hardRockAvailable: false,
    }),
  },
];
