PROJECT : BRIDGE SLIP LINE  JOBNO :1  REF.NO :	
PLAN : PINTOO	
DATE : 04/08/21    TIME : 12:12:48	

FOOTING  DESIGN  SCHEDULE	
SPACEFRAME STRUCTURE	
As Per IS 456 : 2000	

	
	
Schedule of Footings -Flat Footings	
Footing Group 	Column 	PCC Size 	Footing Size 	Total 	Steel 	Steel 	
 	Nos 	X - Y mm	X - Y mm	Depth mm	|| to X mm	|| to Y mm	
FG1	C1	2125 x 2125 	1825 x 1825 	675 	18 - #10 	18 - #10 	
FG2	C2	2125 x 7425 	1825 x 7125 	675 	68 - #10 	18 - #10 	
FG3	C3	2125 x 14625 	1825 x 14325 	675 	136 - #10 	18 - #10 	
